# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: UploadDeployIFlow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:2.4.3
    env:
      HOST_TMN: e1338-tmn.hci.ap1.hana.ondemand.com
      BASIC_USERID: ${{ secrets.DEV_USER_ID }} # When using Basic authentication
      BASIC_PASSWORD: ${{ secrets.DEV_PASSWORD }} # When using Basic authentication
    steps:
      - uses: actions/checkout@v2
      # Set environment variables for update_designtime_artifact.sh
      - run: |
          echo "GIT_SRC_DIR=$GITHUB_WORKSPACE/FlashPipe Demo/wait 15 mins" >> $GITHUB_ENV
      # Upload/Update design time
      - name: 'Update/Upload wait 15 mins to design time'
        run: /usr/bin/update_designtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: wait15mins
          IFLOW_NAME: wait 15 mins
          PACKAGE_ID: FlashPipeDemo
          PACKAGE_NAME: FlashPipe Demo

      # Deploy runtime
      - name: 'Deploy test iflow to runtime'
        run: /usr/bin/deploy_runtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: wait15mins
